[package]
name = "oeis-vis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
bimap = "0.6.3"
cmd_lib = "1.9.5"
indicatif = "0.17.8"
lz4_flex = "0.11.3"
petgraph = "0.6.5"
petgraph-graphml = "3.1.0"
regex = "1.11.0"
walkdir = "2.5.0"
